README.md

* 팀원들에게 PR 템플릿에 관하여 인지 시켜주기 위함입니다.
* PR Template을 구성하였습니다. 
* 최신 Commit으로 업데이트를 하였는지 매번 확인하기 위해서 해당 체크리스트를 포함하였습니다.
* Reviewers이 집중적으로 봐주었으면 좋겠다는 항목도 넣었습니다. 
* 없음
* 없음
* 해당 내용들 자세하게 읽어보시고 review할 때도 템플릿 아래에 있으니 보시고 확인해주시길 바랍니다.
* ex. [P1] : 해당 내용을 반드시 숙지하고, Jira에 해당 이슈 세부 내용도 반드시 확인하여 자세하게 적어주시길 바랍니다.
*
* Review는 특수한 케이스가 아니면 Reviewer로 지정된 시점 기준으로 **2일 이내**에 진행해 …

[SWEP-17] PR Template

---

.github/workflows/deploy-main.yml
.github/workflows/test.yml
@types/environment.d.ts
package.json
prisma/migrations/20250105182531_sweepic_migration_test/migration.sql
prisma/schema.prisma
src/db.config.ts

feature: CI/CD 파이프라인 구축

---

package.json

[SWEP-28] yarn.cmd 수정

---

.editorconfig
.prettierrc.cjs
.vscode/settings.json
README.md
docs/CODE_CONVENTION.md
eslint.config.js
package.json
scripts/build.ts
src/app.ts
src/db.config.ts
tsconfig.json
vscode/settings.json
yarn.lock

close #14 
* #14 이슈 대응
* GTS(Google TypeScript Style) 적용 및 설정
* 코드 컨벤션 문서화
* GTS 가이드 및 포매터, 린터를 적용시켰습니다. (https://github.com/google/gts?tab=readme-ov-file) - `npx gts init`
* tsconfig.json 파일에 해당 gts를 설정하여, 적용되게 하였습니다.
``` json
{
"extends": [
"@tsconfig/node20/tsconfig.json",
"./node_modules/gts/tsconfig-google.json"
],
"compilerOptions": {
"moduleResolution": "Node16",
"module": "Node16"
},
"include": ["src/**/*.ts", "scripts/**/*.ts", "./@types/**/*.d.ts"],
"exclude": ["node_modules", "dist", "build"]
}
```
* eslint.config.js 파일에서 제외 파일과 각종 설정을 하였습니다.
* prettierrc.cjs 파일에서 모듈을 불러와 프리터에 적용시켜, **포매터 온 세이브** 설정을 하면 저장하면 자동으로 맞게 배열되게 작동합니다.
> …

[SWEP-28] GTS 적용 및 코드 컨벤션 문서 정리

---

src/app.ts

[SWEP-35] Swagger host 변경

---

.github/workflows/deploy-main.yml
package.json
scripts/build.ts
src/app.ts
tsconfig.json
yarn.lock

close #27 
* 로컬에서는 스웨거 문서가 접속되지만, 배포 시에 스웨거 문서에 접속이 안됨. - 빌드 시 문제
* 빌드 시에 스웨거 문서가 복사 안되는 것 발견 @GodUser1005 
* [esbuild-plugin-copy](https://www.npmjs.com/package/esbuild-plugin-copy) 참고
* 해당 라이브러리로, 스웨거 문서가 빌드 시에 복사되게 설계함.
* build 파일 변경 (plugins 부분 추가), (outdir 설정이 되어있어서 to 부분은 ./)
```
import esbuild from 'esbuild';
import {copy} from 'esbuild-plugin-copy';
async function build() {
await esbuild.build({
entryPoints: ['./src/app.ts'],
bundle: true,
format: 'cjs',
outdir: './dist',
outExtension: {'.js': '.cjs'},
platform: 'node',
target: 'node20',
minify: true,
keepNames: true,
plugins: [
copy({
assets: [
{
from: …
```

[SWEP-35] 빌드 시 스웨거 문서 미복사 문제 해결 (#27)

---

@types/environment.d.ts
@types/express.d.ts
package.json
src/models/user.model.ts
src/s3/awsS3Client.ts
src/s3/image.deleter.ts
src/s3/image.mover.ts
src/s3/image.uploader.ts
yarn.lock

feature: AWS S3 클라이언트 설정 및 파일 관리 함수 구현

---

@types/environment.d.ts
@types/express.d.ts
package.json
src/models/user.model.ts
src/s3/awsS3Client.ts
src/s3/image.deleter.ts
src/s3/image.mover.ts
src/s3/image.uploader.ts
yarn.lock

close #34
- S3에 접근해서 이미지 업로드, 삭제, 디렉토리 이동 구현하기 (API 구현 X)
- 설치한 라이브러리
- multer ("^1.4.5-lts.1"): 파일 업로드를 처리하기 위한 미들웨어
- multer-s3 ("^3.0.1"): Multer와 AWS S3를 통합해 업로드된 파일을 S3 버킷에 저장할 수 있도록 지원
- aws-sdk/client-s3 ("^3.726.1"): AWS SDK의 모듈화된 클라이언트로, Amazon S3 서비스와 통신하기 위한 라이브러리
- uuid("^11.0.5”): 범용 고유 식별자(Universally Unique Identifier, UUID)를 생성하는 데 사용되는 라이브러리
- 설치한 타입 패키지
- @types/multer ("^1.4.12"): TypeScript에서 multer 라이브러리를 사용할 때 타입 정의 제공
- @types/multer-s3 ("^3.0.3"): TypeScript에서 multer-s3 라이브러리를 사용할 때 타입 정의 제공
- src/s3 디렉토리를 만들어 AWS S3 이미지 관리 함수들을 정리하였습니다.
- models 디렉토리를 생성해 prisma의 User와 매핑하는 User 모델을 추가하였습니다. 이는 임의로 생성한 모델로 이후 데이터베이스 …

[SWEP-43] AWS S3 파일 관리 함수 구현

---

.vscode/settings.json
prisma/migrations/20250115104835_test/migration.sql
prisma/migrations/20250115115450_tag_content_limit_10/migration.sql
prisma/migrations/20250115144526_add_challenge/migration.sql
prisma/schema.prisma
src/models/user.model.ts

chore: prisma 스키마 생성 및 RDS 마이그레이션 적용

---

src/app.ts
src/controllers/memo-folder.controller.ts
src/dtos/memo-folder.dto.ts
src/dtos/memo-image.dto.ts
src/models/memo-folder.model.ts
src/s3/get-presigned-url.ts

req.file MulterS3File 타입 지정, 구조분해 및 Shorthand Property 적용

refactor: req.file MulterS3File 타입 지정, 구조분해 및 Shorthand Property 적용

---

src/auth.config.ts

[SWEP-40] return type 지정

---

src/auth.config.ts
src/entities.ts

[SWEP-40] entities 파일 생성 및 타입 정의

---

src/app.ts
src/auth.config.ts
src/models/auth.entities.ts
src/routers/auth.routers.ts

entities파일 위치변경 및 라우터 설정

---

src/auth.config.ts

구조분해할당 및 shorthand property적용

---

src/app.ts
src/routers/auth.routers.ts

close #76 
소셜 로그인 사용자 정보 반환 관련 문제 해결
1. app.ts에서 라우터 가장 위에 passport 초기화를 해야 함
2. auth.routers.ts에서 serializeUser부분이랑 deserializeUser부분에서의 User가 일치하지 않음
(과정 설명)
- 사용자가 로그인 성공 시 done으로 serializeUser에 넘겨주고 User객체 전체를 session에 저장하게 됨
- 이후 로그인이 되어있을 경우 모든 사용자 페이지를 접근할 경우 deserializeUser가 발생
- deserializeUser에서는 아까 저장된 session값을 이용해 사용자 프로필을 찾아 req에 리턴해줘야 함
* 
*
*에러 발생
* 에러 고친 후
잘 들어오는 걸 확인할 수 있음
*
*
*
* Reviewer 분들은 좋은 …

[SWEP-59] 소셜 로그인 오류 해결

---

.github/workflows/deploy-main.yml
package.json
scripts/build.ts
src/app.ts
yarn.lock

* fix: 빌드 시 스웨거 문서 미복사 문제 해결 (#27)
* [SWEP-28] GTS(Google Typescript Style) 연결결
* [SWEP-26] 리드미 파일 추가
* [SWEP-28] GTS 번역본 등록
* [SWEP-28] lint 실행 에러 해결결
* [SWEP-28] lint 에러 재해결
* [SWEP-28] yarn.cmd 수정정
* [SWEP-28] lint, fix 시 parser 에러 해결
* [SWEP-28] 컴파일 결과물 파일 미생성
* [SWEP-35] Swagger 도메인 연결 (/api-docs)
* [SWEP-35] Swagger 연결 에러 해결결
* fix: 불필요 라이브러리 해제
* [SWEP-35] Swagger host 변경
* [SWEP-35] build 에러 (swagger 미복사 문제)
* [SWEP-35] 워크플로 브랜치 변경 (test 시 develop으로 변경을 원위치)
* fix: 오타 해결
* [SWEP-35] tsconfig.js에 빌드 파일 제외
* 
*
*
*
> 개발 과정에서 다른 분들의 의견은 어떠한지 궁금했거나 크로스 체크가 필요하다고 느껴진 코드가 …

[SWEP-35] 빌드 시 스웨거 문서 미복사 문제 해결 (#27) (#28)

---

src/controllers/memo-createFolderOCR.Controller.ts
src/controllers/memo-folder.controller.ts
src/controllers/memo-image.controller.ts
src/dtos/memo-folder.dto.ts
src/dtos/memo-image.dto.ts
src/models/memo-folder.model.ts
src/models/memo-image.model.ts
src/repositories/memo-folder.repository.ts
src/repositories/memo-image.repository.ts
src/routers/memo.router.ts
src/s3/image.mover.ts
src/s3/image.uploader.ts
src/services/memo-folder.service.ts
src/services/memo-image.service.ts

- 메모 폴더 이름 수정
- 메모 폴더 삭제
- 메모 사진 이동
- 메모 사진 삭제
- 메모 텍스트 수정

feature: 메모장 수정 및 삭제 API 구현

---

.github/workflows/deploy-main.yml
package.json

[SWEP-67] 1차 배포 에러 해결

---

src/controllers/challenge.controllers.ts
src/controllers/challenge.location.controllers.ts
src/controllers/challenge.weekly.controllers.ts
src/dtos/challenge.dtos.ts
src/models/challenge.entities.ts
src/repositories/challenge.repositories.ts
src/repositories/weekly.repositories.ts
src/routers/challenge.router.ts
src/services/challenge.location.services.ts
src/services/challenge.services.ts
src/services/challenge.weekly.services.ts

* 날짜 기반 챌린지 생성
* 날짜 기반 챌린지 불러오기
* 파일들을 각각의 목적에 맞게 모듈화를 재작업했습니다.
* 위치 챌린지는 challenge.location으로, 날짜 챌린지는 challenge.weekly로, 공용은 challenge로
* 공용으로 사용할 수 있는 api는 생성과 삭제입니다. 추후에 챌린지 수락, 완료 기능이 추가될 예정입니다.
* 현재 swagger에 오류가 있는 관계로 postman으로 테스트하였습니다.
* 
* 모듈화가 진행됨에 따라 일부 함수들의 이름이 바뀌었습니다. 또한 코드의 통일성을 위해 함수와 인터페이스의 이름들을 목적에 맞게 수정하였습니다.
* 라우팅을 진행하였습니다.
* swagger와 라우터 부분에 어색한 부분이 있다면 알려주세요.
* 
* Reviewer 분들은 좋은 코드를 발견한 경우, …

[SWEP-52] 날짜 기반 챌린지

---

src/controllers/user.controller.ts
src/routers/user.router.ts

온보딩 API 변경사항

---

src/controllers/user.controller.ts

[SWEP-63] 에러 헨들링 통일

---

src/auth.config.ts

[SWEP-63] 에러메세지 수정2

---

src/app.ts
src/controllers/memo-folder.controller.ts
src/controllers/memo-image.controller.ts
src/errors.ts
src/s3/image.uploader.ts
src/services/memo-folder.service.ts
swagger/openapi.json

누락된 tag-ai(@jonaeunnn 파트) 라우팅 등록 - app.post('/image/ai', labelDetectionController);

fix: tag-ai 라우팅 등록

---

src/app.ts
src/controllers/memo-folder.controller.ts
src/controllers/memo-image.controller.ts
src/errors.ts
src/repositories/memo-folder.repository.ts
src/repositories/memo-image.repository.ts
src/s3/image.mover.ts
src/s3/image.uploader.ts
src/services/memo-folder.service.ts
src/services/memo-image.service.ts
swagger/openapi.json

close #128 
- 메모 텍스트 수정 API에서 폴더 ID로 조회했을 때 null을 반환받을 경우 FolderNotFoundError 커스텀 에러 처리한다.
- 메모장의 모든 API에 대해 Swagger 문서에 400, 404, 409 에러 코드에 대한 실패 응답 예시를 작성한다.
- 메모 텍스트 수정 API - 존재하지 않는 폴더 ID로 조회했을 경우 에러 처리
```
// src/services/memo-folder.service.ts
export const memoTextUpdate = async (userId: bigint, folderId: bigint, body: BodyToMemoTextToUpdate): Promise<MemoTextImageListResponseDto> => {
const folder = await getMemoFolder(folderId);
if (folder === null) {
throw new FolderNotFoundError({folderId});
}
const updatedMemoText = await updateMemoText(userId, folderId, body);
return responseFromMemoTextImageList(updatedMemoText);
};
```
```
// …
```

[SWEP-74] 메모장 텍스트 수정 API 에러 처리 추가 및 swagger 실패 응답 예시 작성 (#129)

---

src/controllers/user.mypage.controllers.ts
src/repositories/mypage.repository.ts
src/routers/mypage.routers.ts
src/services/mypage.service.ts

[SWEP-83] 사용자 로그아웃API

---

src/repositories/mypage.repository.ts
src/routers/mypage.routers.ts

[SWEP-83] 유저 상태 변경

---

src/app.ts
src/controllers/trust.controller.ts
src/repositories/trust.repositories.ts
src/routers/trust.router.ts
src/services/trust.service.ts

[SWEP-58] 휴지통 API

---

src/controllers/user.mypage.controllers.ts
src/repositories/mypage.repository.ts
src/routers/mypage.routers.ts
src/services/mypage.service.ts

close #153 
* 사용자 로그아웃 기능 구현
*mypageRouter에 '/user/mypage/logout' 라우터 추가)
*mypageController
*mypageService
*mypageRepository
*
*
*
*
* P2 : 반영을 적극적으로 고려해 주시면 …

[SWEP-83] 사용자 로그아웃 구현

---

src/controllers/tsoaImage.controller.ts
src/controllers/tsoaTag.controller.ts
src/dtos/tsoaTag.dto.ts
src/models/tsoaTag.model.ts
src/repositories/tsoaImage.repository.ts
src/repositories/tsoaTag.repository.ts
src/routers/tsoaRoutes.ts
src/services/tsoaTag.service.ts
swagger/swagger.json

* 특정이미지에 대한 연관된 태그들을 조회합니다.
* tsoaTag.controller.ts
mediaId를 Path Variable로 받고 로그인된 userId 정보를 이용해
DTO로 감싼뒤
특정이미지의 태그들을 가져오기위해 service layer인 findTagsFromImage로 해당 DTO를 넘겨줍니다
* tsoaTag.dto.ts
위에서 해당하는 DTO 인터페이스입니다.
* tsoaTag.service.ts
이 부분에서는 컨트롤러로 부터 받은 DTO를 이용해 Repository로 태그들을 찾도록 합니다.
Repository로 부터 받은 Id관련 내용들은 bigint를 string으로 변환해줍니다.
* tsoaTag.repository.ts
이 부분은 데이터베이스에서 해당 태그들을 가져오는 쿼리로 구현한 API의 핵심 동작 로직입니다.
쿼리를 간단히 요약 하자면
userId와 mediaId에 해당하며 활성화된 특정 이미지의 태그들중 활성화된 태그들의 태그내용과 해당 태그의 카테고리id및 태그타입을 가져옵니다. 그리고 이 태그들은 tagCategory의 id의 따라 오름차순 정렬 됩니다.
* tsoaTag.model.ts
이 부분은 응답 형식에 대한 인터페이스 입니다.
> 기능을 실행했을 때 정상 동작하는지 여부를 확인하고 스크린 샷을 …

[SWEP-70] 이미지의 태그조회 API

---

src/controllers/trust.controller.ts
src/repositories/trust.repositories.ts
src/services/trust.service.ts
src/utils/tag.utils.ts

[SWEP-58] 성공 응답에 status포함

---

src/routers/mypage.routers.ts

[SWEP-58] mypage 필요없는 라우터 삭제

---

src/controllers/trust.controller.ts
src/services/trust.service.ts

[SWEP-58] 에러 형식 수정

---

src/ai/ai-upload.ts
src/controllers/memo-createFolderOCR.Controller.ts
src/controllers/memo-updateFolderOCR.Controller.ts
src/controllers/tsoaImage.controller.ts
src/controllers/tsoaTag.controller.ts
src/controllers/user.mypage.controllers.ts
src/dtos/tsoaImage.dto.ts
src/dtos/tsoaTag.dto.ts
src/models/memo-OCR.model.ts
src/models/tsoaImage.model.ts
src/models/tsoaTag.model.ts
src/repositories/memo-OCR.repositoy.ts
src/repositories/mypage.repository.ts
src/repositories/tsoaImage.repository.ts
src/repositories/tsoaTag.repository.ts
src/routers/memo.router.ts
src/routers/mypage.routers.ts
src/routers/tsoaRoutes.ts
src/services/memo-ocrService.ts
src/services/mypage.service.ts
src/services/tsoaImage.service.ts
src/services/tsoaTag.service.ts
swagger/swagger.json

close #167 
* 이미지 데이터를 DB에 생성하는 API를 구현했습니다.
* tsoaImage.controller.ts
body로 부터 mediaId와 timestamp를 받아 userId와 함께 이미지데이터를 생성을 위한 컨트롤러 입니다.
이를 통한 응답은 생성한 이미지의 imageId 혹은 이미 존재했던 이미지라면 해당 이미지의 imageId를 출력합니다.
만약 이미지가 존재하지만 휴지통에 있던거라면 잘못된 요청으로 인식합니다.
* tsoaImage.dto.ts
요청으로 부터 받은 데이터들을 DTO로 감싸주는 DTO 파일입니다.
* tsoaImage.model.ts
응답 success에 들어가는 응답 인터페이스입니다.
* tsoaImage.service.ts
서비스 로직입니다.
findImage를 통해 먼저 찾고 만약 발생한 에러에대해 에러코드가 'P2025'라는 건 찾지 못했다는 걸 의미하기에
찾지 못하면 insertImage를 수행하여 이미지 데이터를 추가하고 생성된 이미지의 id를 반환합니다.
이외의 에러들은 위로 던집니다.
* tsoaImage.repository.ts
위는 findImage 입니다.
mediaId와 userId를 통해 이미지를 찾고 만약 없다면 findUniqueOrThrow에서 에러코드 'P2025'와 함께 …

[SWEP-71] 이미지 데이터 생성 API 구현

---

src/controllers/trust.controller.ts
src/controllers/user.mypage.controllers.ts

[SWEP-58] 스웨거 문서 작성

---

src/controllers/trust.controller.ts

[SWEP-58] 사진삭제 스웨거 주석 작성

---

src/controllers/trust.controller.ts
src/controllers/user.mypage.controllers.ts

[SWEP-58] 스웨거 문서 변경

---

src/s3/image.uploader.ts

- multer 미들웨어(imageUploader) 로직 개선
- 기존 코드: async/await을 사용해 비동기 작업을 동기적으로 실행
- 개선된 코드: Promise.all([...])을 사용하여 비동기 작업을 효율적으로 처리하고 .then()과 .catch()를 활용해 콜백 기반의 에러 핸들링을 개선한다.

fix: 메모장 사진 업로드 및 저장 로직 개선

---

src/controllers/trust.controller.ts
src/repositories/trust.repositories.ts
src/routers/trust.router.ts
src/services/trust.service.ts

[SWEP-58] 휴지통 API 변경사항

---

config/tsoa.json
src/auth.config.ts

* 콜백주소에서 도메인으로 수정하였습니다
*
*
*
*
*
#
---

[SWEP-104] 카카오 로그인 콜백 주소 수정

---

src/auth.config.ts

fix: 최초로그인시 유저상태 2로 설정
